
[functions.deploy-from-hashnode]
enabled = true
verify_jwt = false
import_map = "./functions/deploy-from-hashnode/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/deploy-from-hashnode/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/deploy-from-hashnode/*.html" ]
